### ISSUE TITLE
typo in example: should be 'set' instead of 'do'

### ISSUE THREAD

**Issue by adaptun** [nlzv/isc_zip#4]
instead of

    do zip=##class(%zip).open("/mnt/tmp/zip/testunpack/test.zip")

should be

    set zip=##class(%zip).open("/mnt/tmp/zip/testunpack/test.zip")

https://github.com/nlzv/isc_zip/blob/3dad2e4191bf53457cefcfbf2349cdd464a9633e/_Library.zip.class.xml#L22

**Comment by nlzv** [comment]
fixed
